server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: "order-1"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/orders_database
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
    mode: never # чтобы работал liquibase
    continue-on_error: false

#liquibase:
#   enabled: true
#   drop-first: false
#   change-log: classpath:db/changelog/db.changelog-master.xml
#   default-schema: public
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: public

topic:
  send-order: sandbox